---
- name: Install base sytem packages that every server needs
  apt: name={{ item }} state=installed update_cache=true
  with_items: base_apt_packages

# http://stackoverflow.com/questions/5585875/what-is-the-official-preferred-way-to-install-pip-and-virtualenv-systemwide
- name: Install pip and virtualenv
  shell: >
    curl --silent --show-error --retry 5
    https://raw.github.com/pypa/pip/master/contrib/get-pip.py |
    sudo python2.7

- name: pip install base Python packages
  pip:  name={{ item }} state=present
  with_items: base_pip_packages
