---
- name: symlink nginx.conf
  file: path=/var/www state=directory owner={{ user }}

- name: Install web app conf file
  template: >
    src={{ app_name }}.conf.j2
    dest=/etc/nginx/sites-available/{{ app_name }}.conf

- name: Enable csvserver via symlink
  file: >
    src=/etc/nginx/sites-available/csv_server.conf
    dest=/etc/nginx/sites-enabled/csv_server.conf
    owner={{ user }} group={{ user }} state=link

